name: Bandit Security Analysis

on:
  push:
    branches:
      - main

jobs:
  security-analysis:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Setup Python and Install Bandit
      - name: Install Python and Bandit
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip -y
          pip3 install bandit

      # Step 3: Run Bandit Security Analysis
      - name: Run Bandit Scan and Fail for >20 L1 Issues
        run: |
          bandit -r . -f json -o bandit_results.json
          critical_issues=$(jq '[.results[] | select(.issue_severity == "HIGH")] | length' bandit_results.json)
          if [ "$critical_issues" -gt 20 ]; then
            echo "Critical Level 1 issues exceed the allowed threshold of 20. Failing the build."
            exit 1
          else
            echo "Critical Level 1 issues are within the threshold. Build passed."
          fi
