name: SAST Pipeline with CodeQL

on:
  push:
    branches:
      - main

jobs:
  sast-and-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python  # Replace with your project’s language(s) (e.g., javascript, java)

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "SAST Analysis"
