name: SAST Pipeline with Bandit on Windows

on:
  push:
    branches:
      - main

jobs:
  sast-and-validation:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace this with the Python version required for your project

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit Scan
        run: |
          bandit -r . -f json -o bandit-report.json

      - name: Print Bandit Report
        run: type bandit-report.json

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-report.json
