name: Bandit Security Scan (Windows)

on:
  push:
    branches:
      - main

jobs:
  security-analysis:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Setup Python and Install Bandit
      - name: Install Python and Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      # Step 3: Run Bandit Security Scan
      - name: Run Bandit Scan and Check L1 Issues
        run: |
          bandit -r . -f json -o bandit_results.json
          $critical_issues = (Get-Content bandit_results.json | ConvertFrom-Json | % { $_.results } | Where-Object { $_.issue_severity -eq "HIGH" }).Count
          if ($critical_issues -gt 20) {
            Write-Host "Critical Level 1 issues exceed the allowed threshold of 20. Failing the build."
            exit 1
          } else {
            Write-Host "Critical Level 1 issues are within the threshold. Build passed."
          }
