name: SAST Pipeline

on:
  push:
    branches:
      - main

jobs:
  sast-and-validation:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Add SonarScanner to Path (Manual Configuration)
      - name: Configure SonarScanner
        run: |
          setx PATH "%PATH%;C:\Users\u111606\anki2129\sonar-scanner-4.6.2\bin"

      # Step 3: Run SonarScanner
      - name: Run SonarScanner
        run: |
          sonar-scanner ^
            -Dsonar.projectKey=ankithadv21 ^
            -Dsonar.sources=. ^
            -Dsonar.host.url=https://sonarcloud.io ^
            -Dsonar.login=b61fe1f677f741dc723d4614ef0bf8b609fc6937

      # Step 4: Validate Critical L1 Issues
      - name: Validate L1 Issues
        run: |
          $CRITICAL_ISSUES = (Get-Content .sonarqube/out/report-task.txt | ConvertFrom-Json).issues.l1
          if ($CRITICAL_ISSUES -gt 20) {
            Write-Host "Critical L1 issues exceed the allowed threshold of 20. Failing build."
            exit 1
          } else {
            Write-Host "Critical L1 issues are within the allowed threshold. Build passed."
          }
