name: Bandit Security Scan

on:
  push:
    branches:
      - main

jobs:
  security-analysis:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Install Python and Bandit
      - name: Setup Python and Install Bandit
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip -y
          pip3 install bandit

      # Step 3: Run Bandit
      - name: Run Bandit Security Analysis
        run: |
          bandit -r .
